---
- hosts: master
  become: True
  tasks:
 
   - name: Ensure EPEl release is installed 
     dnf:
       name: epel-release.noarch
       state: latest

   - name: install the nginx rpm from a remote repo
     dnf:
       name: 'https://packages.icinga.com/epel/icinga-rpm-release-8-latest.noarch.rpm'
       state: present
       disable_gpg_check: True

   - name: install core dependency for power tool
     dnf:
       name: 
         - dnf-plugins-core
         - perl
       state: present

   - name: run command dnf --set-enabled PowerTools
     dnf: 
       name: 'dnf-command(config-manager)'
       enablerepo: powertools
       state: present

   - name: Power tools enable repo
     command: dnf config-manager --set-enabled powertools


   - name: Installing icinga2 packages
     dnf:
       name: icinga2
       state: present

   - name: Start and Ennable service
     systemd:
       state: started
       name: icinga2
       enabled: yes

   - name: Install Nagios-plugins
     dnf:
       name: nagios-plugins-all
       state: present

   - name: install Icinga2-selinux
     dnf:
       name: icinga2-selinux
       state: present

   - name: Install Icinga Vim
     dnf:
       name: vim-icinga2
       state: present

   - name: install Icinga2 nano
     dnf:     
       name: nano-icinga2
       state: present

   - name: Install configure and start mariaDB services 
     include: maria_db.yml

  handlers:
    - name: import icinga schema
      mysql_db:
        name: icinga
        state: import
        target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
