---
# tasks file for icinga
     - name: install epel repository
       dnf:
         name: 'https://packages.icinga.com/epel/icinga-rpm-release-8-latest.noarch.rpm'
         state: latest
         disable_gpg_check: yes

     - name: install dnf-command
       dnf:
         name: 'dnf-command(config-manager)'
         state: latest
    
     - name: install config manager dependencies 
       dnf:
         name: 
           - dnf-plugins-core
         state: present

     - name: enable PowerTolls repo
       yum_repository:
         name: powertools
         description: CentOS Linux 8 - PowerTools
         baseurl: http://mirror.centos.org/$contentdir/$releasever/PowerTools/$basearch/os/
         enabled: yes
         state: present

     - name: install epel-release
       dnf:
         name: epel-release
         state: present

     - name: install icinga2
       dnf:
         name: icinga2
         state: present
     - name: install icinga-selinux
       dnf: 
         name: icinga2-selinux
         state: present

     - name: start and enable icinga2
       systemd:
         name: icinga2
         state: started
         enabled: yes

     - name: install nagios-plugins
       dnf:
         name: nagios-plugins-all
         enablerepo: powertools
         state: present
          
     - name: install icinga-vim
       dnf:
         name: vim-icinga2
         state: present

    
