---
# tasks file for icingaweb
- name: ensure httpd is installed
  dnf:
    name: httpd
    state: present

- name: ensure httpd is started and enabled
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Disable SELinux
  selinux:
    state: disabled


- name: ensure firewalld  is installed
  dnf:
    name: firewalld
    state: present
 
- name: ensure firewalld is enabled and started 
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: open port 80 443 and 22 to accept incomming traffics
  firewalld:
    port: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp
    - 22/tcp
    - 3306/tcp
    - 5665/tcp

- name: configure default apache page
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache

- name: install icingaweb
  dnf:
    name:
      - icingaweb2
      - icingacli
      - icinga2-selinux
      - icingaweb2-selinux
    state: present

- name: update mysql-ldo config
  template:
    src: templates/mysql-ldo.j2
    dest: /etc/icinga2/features-available/ido-mysql.conf
  notify: restart icinga2


- name: Enable ido-mysql feature
  icinga2_feature:
    name: ido-mysql
    state: present

- name: configure icinga api user
  template:
    src: templates/api-users.conf.j2
    dest: /etc/icinga2/conf.d/api-users.conf
  notify:
    - restart icinga2
    - setup api user

